std_msgs/Header header


float64 speed
float64 throttle
float64 steering
float64 brake

geometry_msgs/Vector3 env_position
float64 latitude
float64 longitude
float64 altitude
geometry_msgs/Vector3 gravity
float64 air_pressure
float64 temperature
float64 air_density

geometry_msgs/Vector3 position
geometry_msgs/Quaternion orientation
geometry_msgs/Vector3 linear_velocity
geometry_msgs/Vector3 linear_acceleration
geometry_msgs/Vector3 angular_velocity
geometry_msgs/Vector3 angular_acceleration

